# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    env:
      COMMENT_APPID: ${{ secrets.COMMENT_APPID }}
      COMMENT_APPKEY: ${{ secrets.COMMENT_APPKEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v2
        with:
          secretId: ${{ secrets.TCB_SECRETID }}
          secretKey: ${{ secrets.TCB_SECRETKEY }}
          envId: ${{ secrets.ENVID }}
